### PR TITLE
Python4Delphi - Compiling for Android

### PR DESCRIPTION
**Pull request by lmbelo**
### Framework independency (FMX|VCL)    

       > VCL and FMX has been separated into framework specific files.

### Compiling for Android   

       > PythonEngine components is now available for Android platform.

### Under development

- FMX wrappers

**_Notes_**

> P4DEngine package is a framework independent layer;  

> VclP4DComp and FmxP4DComp packages are framework specific layer; 

> Framework specific behaviors are provided for P4DEngine via ServicesProvider.TServicesProvider

### CODE REVIEW

**Comment by pyscripter** [comment]
Could you please split the changes into smaller PRs.   
That way it will be so much easier to review and evaluate each one.

**Comment by lmbelo** [comment]
It seems too much code to review, but is almost all about new packages and code split. Behavioral changes are minimal.

**Comment by pyscripter** [comment]
Still, please spit the PR into smaller ones.
e.g. 
- fixes (each one separately)
- refactorings
- FMX stuff
- FatalMsg etc.

There is no way I will commit everything together.

**Comment by lmbelo** [comment]
Understood. I'm working on it.

**Pull request closed without merging**
