### PR TITLE
Vclpackages

### PR DESCRIPTION
**Pull request by lmbelo**
<h3>New VCL packages for VCL dependents</h3>

 - Removed TPythonGUIInputOutput component from framework independent packages and added to VCL packages

### CODE REVIEW

**Comment by pyscripter** [comment]
Thank you.  Looks good.   I will have another look and then I will merge.

**Comment by pyscripter** [comment]
Do you need to include hpp files?  They are automatically generated by Delphi.

**Comment by pyscripter** [comment]
Installation instructions need to be updated as well.

**Comment by lmbelo** [comment]
> Do you need to include hpp files? They are automatically generated by Delphi.

I do might remove them and include into .gitignore

**Comment by lmbelo** [comment]
> Installation instructions need to be updated as well.

We shall update it after merge accepted

**Comment by lmbelo** [comment]
> > Do you need to include hpp files? They are automatically generated by Delphi.
> 
> I do might remove them and include into .gitignore

It is alredy set in .gitignore. It comes from legacy. I did delete them now.

**Pull request merged**
