### PR TITLE
TDynamicDLL as a separate unit + improvements

### PR DESCRIPTION
**Pull request by idanmiara**
I'm using your TDynamicDll as a base for other dlls that I use.
Here are some additions and fixes to make TDynamicDLL more generic

### CODE REVIEW

**Comment by imiara** [comment]
Hi,
I'm wondering if you're considering this pull request or should I keep this class in a different repo.
Idan.

**Comment by pyscripter** [comment]
I am still pondering about this.  I would like to have a closer look to both of your PRs but I have been quite busy.  Sorry for taking so long...

**Comment by imiara** [comment]
Ok, thanks.

**Comment by idanmiara** [comment]
Hi there!
I'm wondering if I should fork DynamicDLL.pas as I'm using it to import a different DLL.
https://github.com/talos-gis/gdal4delphi
Are you still considering this PR?

**Comment by pyscripter** [comment]
Feel free to do that.

**Pull request closed without merging**
