### PR TITLE
A lot of stuff

### PR DESCRIPTION
**Pull request by cutec-chris**
I know, this is a bit messy.
Thats all changes since i use p4d in Lazarus
Maybe you can merge it partially

### CODE REVIEW

**Comment by pyscripter** [comment]
Thanks a lot fro the PR.
The current version compiles with Lazarus 1.8 on Windows and probably on Linux (I have compared it with https://github.com/Alexey-T/Python-for-Lazarus and did not see any significant differences).  It also supports python up to 3.7.

Could you please break down the above in a series of smaller focused PRs explaining the rational for each requested change.

Also please note that I am not interested in further complicating the code trying to support old versions of Lazarus.  Lazarus is free and there is nothing preventing people from upgrading.

**Comment by cutec-chris** [comment]
That Lazarus is free is not the only reason to not support old versions. For me at example i have some code that dont work correct with fpc > 3.0.0, also on raspberry pi lazarus with newer Version has some problems in special cases. 

and its only a view lines of code...

i at time havend the time to clean up the pull request but i understand that you want an cleaner version and when i get the time ill male one

**Comment by cutec-chris** [comment]
Btw. your Version dont compiles with lazarus in linux the last commit fixes this.

**Comment by pyscripter** [comment]
Delphi does not understand the following syntax.  It would break Delphi compatibility. 
{$IFNDEF **CPUX86 OR CPUX86_64**} 
If you want to test for the presence of an ARM processor use the CPUARM define.
Delphi understands CPUARM, CPUARM32 and CPUARM64.

**Comment by pyscripter** [comment]
Please do not forget that DELPHI also targets ARM and Linux.  Your fix should work with both Delphi and FPC and in any case should not break Delphi.

**Comment by cutec-chris** [comment]
fixed (hopefully)

**Comment by pyscripter** [comment]
I have manually committed the change in MaksFPUException.  Thanks.

**Comment by pyscripter** [comment]
I will close this PR.  Please feel free to submit new more focused PRs.

**Pull request closed without merging**
