### PR TITLE
WrapDelphi.CreateVarParam with object - a small helpful overload

### PR DESCRIPTION
**Pull request by mrcsms**
... function  CreateVarParam(PyDelphiWrapper : TPyDelphiWrapper; AObject: TObject) : PPyObject; overload;

### CODE REVIEW

**Comment by pyscripter** [comment]
Could you please describe a use case or even better a unit test that should pass?

**Comment by mrcsms** [comment]
it's not very common - for example, TcxGrid from DevExpress has an event defined as:
TcxGridGetPropertiesEvent = procedure(Sender: TcxCustomGridTableItem; ARecord: TcxCustomGridRecord; var AProperties: TcxCustomEditProperties) of object;
so event handler code use this case of CreateVarParam for passing AProperties to python side

**Comment by pyscripter** [comment]
I am happy to merge this, but is it unreasonable to ask to provide a unit test (in WrapDelphiTest.pas) before merging?  This would serve as a documentation for users.

**Comment by mrcsms** [comment]
you are right, code should be covered by unit tests, I'll prepare sth

**Comment by mrcsms** [comment]
finally i added a test for this function - but to take a step forward, this test covers more general event handlers in p4d

**Pull request merged**
