### PR TITLE
Syncrepo

### PR DESCRIPTION
**Pull request by lmbelo**
Added component TPythonGUIInputOutput for Lazarus.

### CODE REVIEW

**Comment by pyscripter** [comment]
Hi Lucas,

Why are you adding the Register method to WrapDelphi.  Earlier you have moved component registration to PythonReg.pas.  It makes sense to use that unit in the Lazarus package as well.  Also at is stands the other Python components will not be registered in Lazarus.

**Comment by lmbelo** [comment]
Hello, @pyscripter.

We were working for Delphi 10.4+, but Delphi 10.3- are still available. Once it isn't using new packages, we must keep components registration as the way it was. It also makes components available for Lazarus.

**Comment by pyscripter** [comment]
Why not use DelphiReg.pas in the 10.3- and fpc packages?

**Comment by lmbelo** [comment]
Because you asked for changes not applying to the other projects. Add Delphi Reg.pas would make it easier and clean.

**Pull request closed without merging**
